### ISSUE TITLE
[Bug][scaleph-ui-react]invalid auth code on local debug environment

### ISSUE THREAD

**Issue by luckymlog** [flowerfine/scaleph#224]
### Already searched before asking?

- [X] I had searched in the [issues](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scaleph Version or Branch

latest dev

### What happened

http://localhost:4200/api/authCode?d=1662176012388返回
{
  "errorMessage": "用户认证不通过！",
  "errorCode": "401",
  "success": false,
  "showType": 4
}

### Error Exception

```log
http://localhost:4200/api/authCode?d=1662176012388返回
{
  "errorMessage": "用户认证不通过！",
  "errorCode": "401",
  "success": false,
  "showType": 4
}
```

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by kalencaya** [comment]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/24804318/188269842-d14da0d9-f201-472c-b89f-d7e5754dbb5e.png">

**Comment by kalencaya** [comment]
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/24804318/188274445-4b9d920d-7c41-463e-9c37-34518e2167d2.png">
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/24804318/188274493-51ce7c87-de6b-4141-8cf6-77c562e0065d.png">
It is an exception caused by axios timeout when request auth code, for which default timeout is 1000ms. It is not bad for people to to fix it, how about you ?

**Comment by luckymlog** [comment]
Request URL: http://localhost:4200/api/authCode?d=1662258099705
Request Method: GET
Status Code: 200 OK
no exception  but  respones
{
  "errorMessage": "用户认证不通过！",
  "errorCode": "401",
  "success": false,
  "showType": 4
}
